title:              Rice Breeding @ LSU AgCenter
email:              Afamoso@agcenter.lsu.edu       
author:             Louisiana Rice Breeding
description:        "Developing new, superior rice varieties for the Louisiana rice industry."
baseurl:            "/website"
url:                "https://lsuricebreeding.com"
imagesurl: "/website/img/gallery/"
thumbsurl: "/website/img/thumbs/"
