title:              Rice Breeding @ LSU AgCenter
email:              Afamoso@agcenter.lsu.edu       
author:             Louisiana Rice Breeding
baseurl:            "/website"
url:                "https://famosolab.github.io"
imagesurl: "/website/img/gallery/"
thumbsurl: "/website/img/thumbs/"
